config/routes.rb
Rails.application.routes.draw do
  root to: "display#index", as: :root

  resources :passwords, controller: "clearance/passwords", only: [ :create, :new ]

  resource :session, controller: "clearance/sessions", only: [ :create ]
  get "sign_in", to: "clearance/sessions#new", as: "sign_in"
  match "sign_out", to: "clearance/sessions#destroy", via: [ :get, :delete ], as: "sign_out"

  if Clearance.configuration.allow_sign_up?
    get "sign_up", to: "clearance/users#new", as: "sign_up"
  end

  resources :accounts, controller: "clearance/users", only: Clearance.configuration.user_actions do
    resource :password,
             controller: "clearance/passwords",
             only: [ :edit, :update ]
  end

  get "oauth", to: "oauth#index", as: :oauth

  mount MissionControl::Jobs::Engine, at: "/jobs"

  namespace :admin do
    root to: "accounts#index"

    resources :accounts
    resources :users
    resources :teams
    resources :bot_users
    resources :channels
    resources :messages
    resources :private_channels
    resources :private_messages, only: [ :index, :show ]
    resources :attachments
    resources :custom_emojis
    resources :emoji_aliases
  end

  scope "/dm" do
    root to: "dm#index", as: :dms
    get "search", to: "private_search#index", as: :search_dms
    get ":private_channel_id", to: "dm#show", as: :private_channel
    get ":private_channel_id/:date", to: "dm#by_date", as: :private_channel_date
  end

  get "search", to: "search#index", as: :search
  get ":channel_id", to: "display#show", as: :channel
  get ":channel_id/:date", to: "display#by_date", as: :channel_date
end

app/models/user.rb
class User < ApplicationRecord
  validates :slack_user, :display_name, presence: true

  has_many :messages, -> { order(posted_at: :asc) }
  has_many :private_messages, -> { order(posted_at: :asc) }
  has_and_belongs_to_many :private_channels
  has_one :account, required: false, dependent: :nullify
end

app/views/users/_form.html.haml
.form-control.w-full
  = form.label :email, class: 'label label-text'
  = form.text_field :email, type: 'email', placeholder: t("helpers.label.password.email"), class: 'input input-bordered w-full'
.form-control.w-full
  = form.label :password, class: 'label label-text'
  = form.password_field :password, placeholder: t("helpers.label.user.password"), class: 'input input-bordered w-full'

app/views/users/new.html.haml
#clearance.sign-up
  %h1.text-2xl.pb-3= t(".title")
  = form_for @user do |form|
    = render partial: '/users/form', object: form
    .form-control
      = form.submit(t("helpers.submit.user.create"), class: 'btn w-full my-6')
    .other-links
      = link_to t(".sign_in"), sign_in_path